import Head from 'next/head'
import React, { FC, ReactNode } from 'react'

type PropsType = {
   title: string | null
   children: ReactNode;
}

const Layout: FC<PropsType> = ({title, children}) => {
   
  return (
    <>
      <Head>
        <title>{title ? title + ' E-shop' : title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={'flex min-h-screen flex-col justify-between'}>
         <header className={'flex h-12 justify-between'}>header</header>
         <main>
           {children}
         </main>
         <footer>footer</footer>
      </div>
    </>
  )
}

export default Layout
